### PR TITLE
Update entities to have an ID field

### LINKED ISSUE #110: Character data should include their id
Hey, I think it would be useful for the character data to include the identifier of the character.

This way, when parsing data from `https://api.genshin.dev/characters/all`, it would be possible to determine the URL for the icon of each character.

Happy to do it myself, if we can agree that this is a useful feature.

### LINKED ISSUE #149: [request] Add short name that used as access key in object with character's data
Hi 👋

When I get data of character with long name (e.g. Kamisato Ayaka), also I want to get image of this character. In this case I need to make request that look like "https://api.genshin.dev/characters/ayaka/icon", but when I'm trying to do it programmatically (js):
```js
const character = {...} // stored character's data got from api
const img = fetch(`https://api.genshin.dev/characters/${character.name}/icon`);
```
request looks like "https://api.genshin.dev/characters/Kamisato%20Ayaka/icon", even if I remove space and convert name to lower case, I can't get image due to mismatch with full name in character's data and short name that used as id for accessing data. In this case name is "Kamisato Ayaka" and short id name is "ayaka"

Solution is simple: I need to use constructions like switch or if-else like:
```js
let idName = "";
// set proper key
if (character.name == "Kamisato Ayaka") {
 idName = "ayaka";
}

// then make request
const img = fetch(`https://api.genshin.dev/characters/${idName}/icon`); // https://api.genshin.dev/characters/ayaka/icon
```
but it looks ugly and not scalable in a long term.

Is it possible to make character's name and key name the same or add id name in character's data?
```json
{
 "id": "ayaka",
 "name": "Kamisato Ayaka"
}
```

### PR DESCRIPTION
**Pull request by SteeledSlagle13**
**Add id fields to all entities**
Field maps to the directory name. This makes it easier to reference image folders if consumers are just using the `GET :type/all` endpoint.
(some entities already had an id field mapping to their directory... this just adds it to all other entities)

- removed \u0009 character from food/de.json -- lint
- removed a en,json file
- added correct data for [blackcliff-agate/en.json](https://github.com/genshindev/api/compare/mistress...strelitziabot:genshin-api:mistress#diff-f1f5d9d74b042c8de26545f818e3137fa5cdfdf18ad56ae2620f296541a49d54)

### CODE REVIEW

**Review by man90es — CHANGES_REQUESTED** [review]
I think it would be much wiser to implement adding those IDs programmatically, rather than worry about adding a correct ID to every existing and future data file

**Comment by man90es** [comment]
I kinda need this feature too, so I'm going to start working on my own version next week if there's no activity from @SteeledSlagle13 until then

**Comment by M4GICB** [comment]
@man90es and @SteeledSlagle13 - is this fixed now with pr https://github.com/genshindev/api/pull/279 ?

**Comment by man90es** [comment]
> @man90es and @SteeledSlagle13 - is this fixed now with pr #279 ?

Yeah we can close this one unless that blackcliff-agate/en.json change is any valuable. My browser freezes when I try to check what that change is

**Comment by M4GICB** [comment]
I was able to check. The blackcliff-agate/en.json change is just adding the id field and all the other changes in the file seem like linter changes.

**Pull request closed without merging**
