### PR TITLE
Added parts of german translation for food.

### PR DESCRIPTION
**Pull request by ghaku**
Again I tried adding as much as I could but sadly I don't have all the food and I couldn't find all the information about it online.

### CODE REVIEW

**Review by JMPJNS — COMMENTED** [review]
should we takle out the english versions from the german translation and in code default to english if a field doesn't exist in other languages maybe?

**Comment by ghaku** [comment]
Sounds like a pretty good idea to me but we gotta see what the repo-owners think about that. I would personally prefer it that way, it would make translation a lot better and faster.

**Comment by ghaku** [comment]
Are we gonna do it this way now or no? Just asking because if so I can start working on the rest of the translation.

**Comment by NurMarvin** [comment]
> should we takle out the english versions from the german translation and in code default to english if a field doesn't exist in other languages maybe?

Pretty sure that's how I did it before. Might have been lost when you re-did the API.
Would love to make it that way again, so I'll be removing the unchanged translations from this PR and then merge it.

**Comment by ghaku** [comment]
Perfect, I'll just remove the english parts the next time I add more translations to this.

**Pull request merged**
